# Generated by Django 5.1 on 2024-09-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipapp', '0003_userprofile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='test',
        ),
    ]
