# Generated by Django 5.1 on 2024-09-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipapp', '0004_remove_userprofile_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can View'), ('can_create', 'Can Create'), ('can_edit', 'Can Edit'), ('can_delete', 'Can Delete')]},
        ),
    ]
