# Generated by Django 5.1 on 2024-08-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipapp', '0008_rename_author_book_author1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author1',
            new_name='author',
        ),
    ]
