# Generated by Django 5.1 on 2024-08-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipapp', '0009_rename_author1_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarian',
            old_name='name',
            new_name='name1',
        ),
    ]
