# Generated by Django 5.1 on 2024-08-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipapp', '0011_rename_name1_librarian_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
