# Generated by Django 5.1 on 2024-08-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipapp', '0003_rename_title1_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='title1',
        ),
    ]
