# Generated by Django 5.1 on 2024-08-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipapp', '0007_rename_title1_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author1',
        ),
    ]
