# Generated by Django 5.1 on 2024-08-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipapp', '0014_rename_publication_year1_author_publication_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='publication_year',
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
