# Generated by Django 5.1 on 2024-09-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0003_user_date_of_birth_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
