# Generated by Django 5.1 on 2024-09-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0005_user_address_user_date_of_birth_user_phone'),
    ]

    operations = [
    ]
