# Generated by Django 5.1 on 2024-09-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0006_auto_20240915_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
