# Generated by Django 5.1 on 2024-09-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0008_remove_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
