# Generated by Django 5.1 on 2024-09-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0009_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
