# Generated by Django 5.1 on 2024-09-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0010_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
    ]
