# Generated by Django 5.1 on 2024-08-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipapp', '0010_rename_name_librarian_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarian',
            old_name='name1',
            new_name='name',
        ),
    ]
